version: '2.3'

services:
  # LUBM data sets
  tracedsparql_lubm_skg:
    image: prohde/virtuoso-opensource-7:7.2.11
    container_name: tracedsparql_lubm_skg
    volumes:
      - ./datasources/lubm/skg:/database
      - ./datasources/virtuoso.ini:/database/virtuoso.ini
    mem_limit: 64g
    ports:
      - '15000:8890'
  tracedsparql_lubm_mkg:
    image: prohde/virtuoso-opensource-7:7.2.11
    container_name: tracedsparql_lubm_mkg
    volumes:
      - ./datasources/lubm/mkg:/database
      - ./datasources/virtuoso.ini:/database/virtuoso.ini
    mem_limit: 64g
    ports:
      - '15001:8890'
  tracedsparql_lubm_lkg:
    image: prohde/virtuoso-opensource-7:7.2.11
    container_name: tracedsparql_lubm_lkg
    volumes:
      - ./datasources/lubm/lkg:/database
      - ./datasources/virtuoso.ini:/database/virtuoso.ini
    mem_limit: 64g
    ports:
      - '15002:8890'

  # WatDiv data sets
  tracedsparql_watdiv_500k:
    image: prohde/virtuoso-opensource-7:7.2.11
    container_name: tracedsparql_watdiv_500k
    volumes:
      - ./datasources/watdiv/500k:/database
      - ./datasources/virtuoso.ini:/database/virtuoso.ini
    mem_limit: 64g
    ports:
      - '15003:8890'
  tracedsparql_watdiv_10M:
    image: prohde/virtuoso-opensource-7:7.2.11
    container_name: tracedsparql_watdiv_10M
    volumes:
      - ./datasources/watdiv/10M:/database
      - ./datasources/virtuoso.ini:/database/virtuoso.ini
    mem_limit: 64g
    ports:
      - '15004:8890'
  tracedsparql_watdiv_100M:
    image: prohde/virtuoso-opensource-7:7.2.11
    container_name: tracedsparql_watdiv_100M
    volumes:
      - ./datasources/watdiv/100M:/database
      - ./datasources/virtuoso.ini:/database/virtuoso.ini
    mem_limit: 64g
    ports:
      - '15005:8890'

  #DBpedia
  tracedsparql_dbpedia:
    image: prohde/virtuoso-opensource-7:7.2.11
    container_name: tracedsparql_dbpedia
    volumes:
      - ./datasources/dbpedia:/database
      - ./datasources/virtuoso.ini:/database/virtuoso.ini
    mem_limit: 64g
    ports:
      - '15006:8890'

  # TracedSPARQL engine
  tracedsparql_engine:
    build: ./code/
    image: sdmtib/tracedsparql_engine:experiments
    container_name: tracedsparql_engine
    volumes:
      - ./api_configs:/inputs/api_configs
      - ./shapes:/inputs/shapes
      - ./results:/results
      - ./datasources/source-description:/TracedSPARQL/Config
      - ./queries:/queries
    mem_limit: 32g

