version: '2.3'

services:
  tracedsparql_engine:
    build: ./code/
    image: sdmtib/tracedsparql_engine:experiments
    container_name: tracedsparql_engine
    volumes:
      - ./api_configs:/inputs/api_configs
    mem_limit: 32g

